---
tags: [spring-cloud, eureka]
projects: [spring-cloud]
---
:spring_boot_version: 1.2.8.RELEASE
:DataSource:
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-service-registration-and-discovery

This guide walks you through the process of standing up and consuming the Netflix Eureka service registry.om

== What you'll build

You'll setup a https://github.com/spring-cloud/spring-cloud-netflix[Netflix Eureka service registry] and then build a client that both registers itself with the registry and uses it to resolve its own host. A service registry is useful because it enables client-side load-balancing and decouples service providers from consumers without the need for DNS.

== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[reveal-gradle]]
[.reveal-gradle]
== Build with Gradle

[[scratch]]
[.use-gradle]
== Build with Gradle

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_system_intro.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_directory_structure_hello.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_both_builds.adoc[]

`eureka-service/build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::https://raw.githubusercontent.com/spring-guides/{project_id}/master/initial/eureka-service/build.gradle[]
----

`eureka-client/build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::https://raw.githubusercontent.com/spring-guides/{project_id}/master/initial/eureka-client/build.gradle[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-gradle-plugin.adoc[]

[[reveal-maven]]
[.reveal-maven]
== Build with Maven

[[use-maven]]
[.use-maven]
== Build with Maven

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_system_intro_maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_directory_structure_hello.adoc[]

`eureka-service/pom.xml`
[source,xml]
----
include::https://raw.githubusercontent.com/spring-guides/{project_id}/master/initial/eureka-service/pom.xml[]
----

`eureka-client/pom.xml`
[source,xml]
----
include::https://raw.githubusercontent.com/spring-guides/{project_id}/master/initial/eureka-client/pom.xml[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-maven-plugin.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]


[[initial]]
== Stand up a Eureka Service Registry
You'll first need a Eureka Service registry. You can use Spring Cloud's `@EnableEurekaServer` to standup a registry that other applications can talk to. This is a regular Spring Boot application with one annotation added to _enable_ the service registry.

`eureka-service/src/main/java/hello/EurekaServiceApplication.java`
[source,java]
----
include::complete/eureka-service/src/main/java/hello/EurekaServiceApplication.java[]
----

When the registry starts up it will complain, with a stacktrace, that there are no replica nodes for the registry to connect to. In a production environment, you will want more than one instance of the registry. For our simple purposes, however, it sufficies to disable the relevant logging.

By default, the registry will _also_ attempt to register itself, so you'll need to disable that, as well.

It's a good convention to put this registry on a separate port when using it locally.

Add some properties to your `eureka-service/src/main/resources/application.properties` to handle all of these requirements.

`eureka-service/src/main/resources/application.properties`
[source,properties]
----
include::complete/eureka-service/src/main/resources/application.properties[]
----


== Talking to the Registry

Now that we've stood up a service registry, let's stand up a client that both registers itself with the registry and uses the Spring Cloud `DiscoveryClient` abstraction to interrogate the registry for it's own host and port. The `@EnableDiscoveryClient` activates the Netflix Eureka `DiscoveryClient` implementation. There are other implementations for other service registries like https://www.consul.io/[Hashicorp's Consul] or https://zookeeper.apache.org/[Apache Zookeeper].

`eureka-client/src/main/java/hello/EurekaClientApplication.java`
[source,java]
----
include::complete/eureka-client/src/main/java/hello/EurekaClientApplication.java[]
----

Whatever implementation you choose, you'll soon see the `eureka-client` registered under whatever name you specify in the `spring.application.name` property. This property is used a lot in Spring Cloud, often in the earliest phases of a service's configuration. This property is used in service bootstrap and so by convention lives in `eureka-client/src/main/resources/bootstrap.properties`  where it's found _before_ `src/main/resources/application.properties`.

`eureka-client/src/main/resources/bootstrap.properties`
[source,properties]
----
include::complete/eureka-client/src/main/resources/bootstrap.properties[]
----

The `eureka-client` defines a Spring MVC REST endpoint, `ServiceInstanceRestController`, that returns an enumeration of all the `ServiceInstance` instances registered in the registry at  `http://localhost:8080/service-instances/a-bootiful-client`. Consult the https://spring.io/guides/gs/rest-service/[Building a RESTful Web Service]  guide to learn more about building REST services with Spring MVC and Spring Boot.

== Test the application

Test the end-to-end result by starting the `eureka-service` first and then, once loaded, starting the `eureka-client`. The `eureka-client` will take about a minute to register itself in the registry and to refresh its own list of registered instances from the registry. All of these thresholds are configurable. Visit the `eureka-client` in the browser, `http://localhost:8080/service-instances/a-bootiful-client`. There, you should see the `ServiceInstance` for the `eureka-client` reflected in the response.


== Summary
Congratulations! You've just used Spring to stand up a Netflix Eureka service registry and to use that registry in a client application.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]
