---
tags: [spring-cloud, eureka]
projects: [spring-cloud]
---
:spring_boot_version: 1.2.8.RELEASE
:DataSource:
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-service-registration-and-discovery
This guide walks you through the process of standing up and consuming the Netflix Eureka service registry.om

== What you'll build

You'll setup a https://github.com/spring-cloud/spring-cloud-netflix[Netflix Eureka service registry]
and then build a client that both registers itself with the registry and uses it to resolve its own host. A service registry
is useful because it enables client-side load-balancing and decouples service providers from consumers without the need for DNS.

== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]


[[initial]]
== Stand up a Eureka Service Registry
You'll first need a Eureka Service registry. You can use Spring Cloud's `@EnableEurekaServer`
to standup a registry that other applications can talk to. This is a regular Spring Boot application with
one annotation added to _enable_ the service registry.

`eureka-service/src/main/java/hello/EurekaServiceApplication.java`
[source,java]
----
include::complete/eureka-service/src/main/java/hello/EurekaServiceApplication.java[]
----

When the registry starts up it will complain, with a stacktrace, that there are no
replica nodes for the registry to connect to. In a production environment, you will want
more than one instance of the registry. For our simple purposes, however, it sufficies to
disable the relevant logging.

By default, the registry will _also_ attempt to register itself, so you'll need to disable that, as well.

It's a good convention to put this registry on a separate port when using it locally.

Add some properties to your `eureka-service/src/main/resources/application.properties` to handle all of these requirements.

`eureka-service/src/main/resources/application.properties`
[source,properties]
----
include::complete/eureka-service/src/main/resources/application.properties[]
----


== Talking to the Registry

Now that we've stood up a service registry, let's stand up a client that both registers itself with the registry and
uses the Spring Cloud `DiscoveryClient` abstraction to interrogate the registry for it's own host and port. The `@EnableDiscoveryClient`
annotation configures whatever `DiscoveryClient` implementation is on the classpath and makes a `DiscoveryClient` implementation available
for use.

`eureka-client/src/main/java/hello/EurekaClientApplication.java`
[source,java]
----
include::complete/eureka-client/src/main/java/hello/EurekaClientApplication.java[]
----

The Eureka implementation registers the current application using whatever name specified by the `spring.application.name` property.
This property is used a lot in Spring Cloud, often in the earliest phases of a service's configuration. By convention, put this
property in a file called `eureka-client/src/main/resources/bootstrap.properties` where it'll be found before `src/main/resources/application.properties`.


== Summary
Congratulations! You've just used Spring to stand up a Netflix Eureka service registry and to use that registry in a client application.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]
