:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-service-registration-and-discovery

This guide walks you through the process of starting and using the Netflix Eureka service
registry.

== What You Will Build

You will set up a
https://github.com/spring-cloud/spring-cloud-netflix[Netflix Eureka service registry] and
then build a client that both registers itself with the registry and uses it to resolve
its own host. A service registry is useful because it enables client-side load-balancing
and decouples service providers from consumers without the need for DNS.

== What You Need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/how_to_complete_this_guide.adoc[]

[[scratch]]
== Starting with Spring Initializr

For all Spring applications, you should start with the https://start.spring.io[Spring
Initializr]. The Initializr offers a fast way to pull in all the dependencies you need for
an application and does a lot of the set up for you.

This guide needs two applications. The first application (the service application) needs
only the Eureka Server dependency.

The second application (the client application) needs the Eureka Server and Eureka
Discovery Client dependencies.

NOTE: For convenience, we have provided build files (a `pom.xml` file and a `build.gradle`
file) at the top of the project (one directory above the `service` and `client`
directories) that you can use to build both projects at once. We also added the Maven and
Gradle wrappers there.

:server-link: https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.5.5&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=service-registration-and-discovery&name=service-registration-and-discovery&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.service-registration-and-discovery&dependencies=cloud-eureka-server
:client-link: https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.5.5&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=service-registration-and-discovery-client&name=service-registration-and-discovery-client&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.service-registration-and-discovery-client&dependencies=cloud-eureka-server,cloud-eureka

You can use this {server-link}[pre-initialized project] (for the service application) or this {client-link}[pre-initialized project] (for the client application) and click Generate to download a ZIP file. This project is configured to fit the examples in this tutorial.

To manually initialize the project:

. Navigate to https://start.spring.io.
This service pulls in all the dependencies you need for an application and does most of the setup for you.
. Choose either Gradle or Maven and the language you want to use. This guide assumes that you chose Java.
. Click *Dependencies* and select *Eureka Server* for the service application and *Eureka Server* and *Eureka Discovery Client* for the client application.
. Click *Generate*.
. Download the resulting ZIP file, which is an archive of a web application that is configured with your choices.

NOTE: If your IDE has the Spring Initializr integration, you can complete this process from your IDE.

NOTE: You can also fork the project from Github and open it in your IDE or other editor.

[[initial]]
== Start a Eureka Service Registry

You first need a Eureka Service registry. You can use Spring Cloud's `@EnableEurekaServer`
to stand up a registry with which other applications can communicate. This is a regular
Spring Boot application with one annotation (`@EnableEurekaServer`) added to enable the
service registry. The following listing (from
`eureka-service/src/main/java/com.example.serviceregistrationanddiscoveryservice/ServiceRegistrationAndDiscoveryServiceApplication.java`)
shows the service application:

====
[source,java]
----
include::complete/eureka-service/src/main/java/com/example/serviceregistrationanddiscoveryservice/ServiceRegistrationAndDiscoveryServiceApplication.java[]
----
====

When the registry starts, it will complain (with a stacktrace) that there are no replica
nodes to which the registry can connect. In a production environment, you will want more
than one instance of the registry. For our simple purposes, however, it suffices to
disable the relevant logging.

By default, the registry also tries to register itself, so you need to disable that
behavior as well.

It is a good convention to put this registry on a separate port when using it locally.

Add some properties to `eureka-service/src/main/resources/application.properties` to
handle all of these requirements, as the following listing shows:

====
[source,properties]
----
include::complete/eureka-service/src/main/resources/application.properties[]
----
====

== Talking to the Registry

Now that you have started a service registry, you can stand up a client that both
registers itself with the registry and uses the Spring Cloud `DiscoveryClient` abstraction
to interrogate the registry for its own host and port. The `@EnableDiscoveryClient`
activates the Netflix Eureka `DiscoveryClient` implementation. (There are other
implementations for other service registries, such as
https://www.consul.io/[Hashicorp's Consul] or https://zookeeper.apache.org/[Apache Zookeeper]).
The following listing (from
`eureka-client/src/main/java/example/serviceregistrationanddiscoveryclient/ServiceRegistrationAndDiscoveryClientApplication.java`)
shows the client application:

====
[source,java]
----
include::complete/eureka-client/src/main/java/com/example/serviceregistrationanddiscoveryclient/ServiceRegistrationAndDiscoveryClientApplication.java[]
----
====

Whatever implementation you choose, you should soon see `eureka-client` registered under
whatever name you specify in the `spring.application.name` property. This property is used
a lot in Spring Cloud, often in the earliest phases of a service's configuration. This
property is used in service bootstrap and, so, by convention lives in
`eureka-client/src/main/resources/bootstrap.properties` where it is found before
`src/main/resources/application.properties`. The following listing shows the
`bootstrap.properties` file:

====
[source,properties]
----
include::complete/eureka-client/src/main/resources/bootstrap.properties[]
----
====

The `eureka-client` defines a Spring MVC REST endpoint (`ServiceInstanceRestController`)
that returns an enumeration of all the registered `ServiceInstance` instances at
`http://localhost:8080/service-instances/a-bootiful-client`. See the
https://spring.io/guides/gs/rest-service/[Building a RESTful Web Service]  guide to learn
more about building REST services with Spring MVC and Spring Boot.

== Test the Application

Test the end-to-end result by starting the `eureka-service` first and then, once that has
loaded, starting the `eureka-client`.

To run the Eureka service with Maven, run the following command in a terminal window (in
the `/complete` directory):

====
[source,bash]
----
./mvnw spring-boot:run -pl eureka-service
----
====

To run the Eureka client with Maven, run the following command in a terminal window (in
the `/complete` directory):

====
[source,bash]
----
./mvnw spring-boot:run -pl eureka-client
----
====

To run the Eureka service with Gradle, run the following command in a terminal window (in
the `/complete` directory):

====
[source,bash]
----
./gradlew :eureka-service:bootRun
----
====

To run the Eureka client with Gradle, run the following command in a terminal window (in
the `/complete` directory):

====
[source,bash]
----
./gradlew :eureka-client:bootRun
----
====

The `eureka-client` will take about a minute to register itself in the registry and to
refresh its own list of registered instances from the registry. Visit the `eureka-client`
in the browser, at `http://localhost:8080/service-instances/a-bootiful-client`. There, you
should see the `ServiceInstance` for the `eureka-client` reflected in the response. If you
see an empty `<List>` element, wait a bit and refresh the page.

== Summary
Congratulations! You have just used Spring to stand up a Netflix Eureka service registry
and to use that registry in a client application.

== See Also

The following guides may also be helpful:

* https://spring.io/guides/gs/rest-service/[Building a RESTful Web Service]
* https://spring.io/guides/gs/serving-web-content/[Serving Web Content with Spring MVC]
* https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/footer.adoc[]
